module.exports= {

babyBasicProfileMapper :(result,req)=>{
     result.hospital_id= req.body.hospital_id,
     result. hospital_name= req.body.hospital_name ,
     result.hospital_branch_name= req.body.hospital_branch_name ,
     result.baby_medical_record_number= req.body.babyMedicalRecord,
     result. baby_mother_medical_record_number=req.body.babyMotherMedicalRecord,
     result.is_update=req.body.is_update
     return result
},

babyGeneralProfileMapper:(result,req)=>{
     result.record_type= req.body.record_type,
     result.baby_admission_type= req.body.baby_admission_type,
     result.baby_birth_date= req.body.baby_birth_date,
     result.study_id= req.body.study_id,
     result.baby_place_of_birth_pin_code= req.body.baby_place_of_birth_pin_code,
     result.baby_place_of_birth_name= req.body.baby_place_of_birth_name,
     result.baby_birth_time_hours= req.body.baby_birth_time_hours,
     result.baby_birth_time_minit= req.body.baby_birth_time_minit,
     result.baby_age_of_admission= req.body.baby_age_of_admission,
     result.baby_apgar_score_one_min= req.body.baby_apgar_score_one_min,
     result.baby_apgar_score_five_min= req.body.baby_apgar_score_five_min,
     result.baby_apgar_score_ten_min= req.body.baby_apgar_score_ten_min,
     result.baby_preterm= req.body.baby_preterm,
     result.baby_condition_yes_eos_los= req.body.baby_condition_yes_eos_los,
     result.baby_condition_rds_yes_no=req.body.baby_condition_rds_yes_no,
     result.baby_gender= req.body.baby_gender,
     result.baby_condition_jaundice_suspect= req.body.baby_condition_jaundice_suspect,
     result.baby_condition_ttnb_suspect= req.body.baby_condition_ttnb_suspect,
     result.baby_condition_lga_suspect= req.body.baby_condition_lga_suspect,
     result.baby_condition_aga_suspect= req.body.baby_condition_aga_suspect,
     result.baby_condition_sga_suspect= req.body.baby_condition_sga_suspect,
     result.baby_shock_aga_suspect= req.body.baby_shock_aga_suspect,
     result.baby_condition_dextrocordia_suspect= req.body.baby_condition_dextrocordia_suspect,
     result.baby_condition_anemia_suspect= req.body.baby_condition_anemia_suspect,
     result.baby_condition_lbw_suspect= req.body.baby_condition_lbw_suspect,
     result.place_of_delivery= req.body.place_of_delivery,
     result.birth_facility= req.body.birth_facility,
     result.baby_gestational_age= req.body.baby_gestational_age,
     result.baby_gestational_age_unit= req.body.baby_gestational_age_unit,
     result.baby_weight_at_birth= req.body.baby_weight_at_birth,
     result.baby_condition_suspect=req.body.baby_condition_suspect,
     result.baby_day_of_event= req.body.baby_day_of_event,
     result.baby_weight_at_admission= req.body.baby_weight_at_admission,
     result.baby_condition_other_if_suspect= req.body.baby_condition_other_if_suspect,
     result.prelim_diagnosis_perinatal=req.body.prelim_diagnosis_perinatal,
     result.prelim_diagnosis_hypoglycemia= req.body.prelim_diagnosis_hypoglycemia,
     result.prelim_diagnosis_hypocalcemia= req.body.prelim_diagnosis_hypocalcemia,
     result.prelim_diagnosis_feeding_intolerence= req.body.prelim_diagnosis_feeding_intolerence,
     result.prelim_diagnosis_gastroenteritis= req.body.prelim_diagnosis_gastroenteritis,
     result.baby_weight_at_admission_unit= req.body.baby_weight_at_admission_unit,
     result.baby_date_of_admission= req.body.baby_date_of_admission
     return result
},

babyMaternalProfileMapper:(result,req)=>{
     result.mother_age= req.body.mother_age,
     result.mother_weight_unit=req.body.mother_weight_unit ,
     result.mother_weight= req.body.mother_weight,
     result.mother_height=req.body.mother_height,
     result.mother_height_unit=req.body.mother_height_unit ,
     result.mother_haemoglobin=req.body.mother_haemoglobin,
     result.mother_bmi=req.body.mother_bmi ,
     result.maternal_blood_pressure=req.body.maternal_blood_pressure ,
     result.maternal_blood_pressure_diastolic=req.body.maternal_blood_pressure_diastolic,
     result.maternal_diabetes=req.body.maternal_diabetes ,
     result.maternal_fever= req.body.maternal_fever,
     result.maternal_fever_unit= req.body.maternal_fever_unit,
     result.maternal_fever_basic=req.body.maternal_fever_basic ,
     result.maternal_thyroid_function=req.body.maternal_thyroid_function ,
     result.maternal_thyroid_function_basic= req.body.maternal_thyroid_function_basic,
     result.maternal_thyroid_function_unit_basic= req.body.maternal_thyroid_function_unit_basic,
     result.maternal_thyroid_function_unit_basic_unit= req.body.maternal_thyroid_function_unit_basic_unit,
     result.more_than_3_vaginal_examinations_during_labor= req.body.more_than_3_vaginal_examinations_during_labor,
     result.rupture_of_membranes_rom_two= req.body.rupture_of_membranes_rom_two,
     result.rupture_of_membranes_rom_one= req.body.rupture_of_membranes_rom_one,
     result.rupture_of_membranes_rom= req.body.rupture_of_membranes_rom,
     result.leaking_pv= req.body.leaking_pv,
     result.smelly_amniotic_fluid= req.body.smelly_amniotic_fluid,
     result.chorioamnionitis=req.body.chorioamnionitis ,
     result.gbs_infection=req.body.gbs_infection ,
     result.colonisation_or_urinary_tract_infection=req.body.colonisation_or_urinary_tract_infection ,
     result.torch_infections= req.body.torch_infections,
     result.type_of_delivery= req.body.type_of_delivery ,
     result.delayed_cord_clamping= req.body.delayed_cord_clamping,
     result.vaginal_swab_culture= req.body.vaginal_swab_culture ,
     result.vaginal_swab_culture_two= req.body.vaginal_swab_culture_two,
     result.vaginal_swab_culture_three= req.body.vaginal_swab_culture_three ,
     result.amniotic_fluid_culture= req.body.amniotic_fluid_culture,
     result.amniotic_fluid_culture_three= req.body.amniotic_fluid_culture_three,
     result.amniotic_fluid_culture_two= req.body.amniotic_fluid_culture_two
     return result
},

babyAppearsMapper : (result , req)=>{
     result. baby_appearance= req.body.baby_appearance,
     result. baby_skin_colour= req.body.baby_skin_colour,
     result.baby_cry_sound= req.body.baby_cry_sound,
     result.baby_cry_sound_status= req.body.baby_cry_sound_status,
     result.hypotonia_muscular_response_one_min_after_birth= req.body.hypotonia_muscular_response_one_min_after_birth,
     result.hypotonia_muscular_response_five_min_after_birth= req.body.hypotonia_muscular_response_five_min_after_birth,
     result.excessive_sleeping=req.body.excessive_sleeping,
     result.hypothermia= req.body.hypothermia,
     result.hypothermia_status=req.body.hypothermia_status,
     result.hypothermia_status_value=req.body.hypothermia_status_value,
     result.baby_feeding_status=req.body.baby_feeding_status,
     result.baby_presence_of_convulsions= req.body.baby_presence_of_convulsions,
     result.baby_jaundice=req.body.baby_jaundice,
     result.breast_feeding_initiation= req.body.breast_feeding_initiation,
     result.kangaroo_mother_care= req.body.kangaroo_mother_care,
     result.umbilical_discharge= req.body.umbilical_discharge
     return result
},

updateBabyRespMapper: (result , req ,baby_respiratory_support)=>{
     result.groaning =  req.body.groaning,
     result.grunting = req.body.grunting,
     result.stridor = req.body.stridor,
     result.retraction = req.body.retraction,
     result.fast_breathing = req.body.fast_breathing,
     result.oxygen_saturation = req.body.oxygen_saturation,
     result.breathing_rate = req.body.breathing_rate,
     result.baby_chest_indrawing = req.body.baby_chest_indrawing,
     result.x_ray_result = req.body.x_ray_result,
     result.x_ray_status_done = req.body.x_ray_status_done,
     result.x_ray_status = req.body.x_ray_status,
     result.x_ray_diagnosis_any_other = req.body.x_ray_diagnosis_any_other,
     result.apnea_diagnosis = req.body.apnea_diagnosis,
     result.apnea_status = req.body.apnea_status,
     result.baby_respiratory_support =baby_respiratory_support,
     result.baby_respiratory_support_if_yes = req.body.baby_respiratory_support_if_yes,
     result.tab_name = req.body.tab_name
     return result
},
updateBabyCVMapper: (result , req )=>{
     result.heart_rate= req.body.heart_rate ,
     result.urine_output=req.body.urine_output,
     result.baby_blood_pressure_mean_arterial_bp= req.body.baby_blood_pressure_mean_arterial_bp,
     result.baby_blood_pressure_upper_limb=req.body.baby_blood_pressure_upper_limb ,
     result.baby_blood_pressure_lower_limb=req.body.baby_blood_pressure_lower_limb ,
     result.capillary_refill_unit=req.body.capillary_refill_unit ,
     result.low_peripheral_pulse_volume=req.body.low_peripheral_pulse_volume ,
     result.cool_peripheries=req.body.cool_peripheries,
     result.two_d_echo_done=req.body.two_d_echo_done ,
     result.two_d_echo_done_if_yes= req.body.two_d_echo_done_if_yes,
     result.baby_on_ionotropes= req.body.baby_on_ionotropes ,
     result.central_line= req.body.central_line,
     result.skin_pustules= req.body.skin_pustules,
     result.infusion_of_blood_products=req.body.infusion_of_blood_products
     return result
},
updateBabyInvestigationMapper :(result , req )=>{
     result.baby_thyroid_status= req.body.baby_thyroid_status,
     result.baby_thyroid_result= req.body.baby_thyroid_result,
     result.baby_blood_glucose= req.body.baby_blood_glucose,
     result.baby_haemoglobin_levels= req.body.baby_haemoglobin_levels,
     result.baby_c_reactive_protien_levels= req.body.baby_c_reactive_protien_levels,
     result.micro_esr=req.body.micro_esr,
     result.baby_procalcitonin_levels=req.body.baby_procalcitonin_levels,
     result.total_leucocute_count_unit=req.body.total_leucocute_count_unit,
     result.total_leucocute_count=req.body.total_leucocute_count,
     result.absolute_neutrophil_count=req.body.absolute_neutrophil_count,
     result.absolute_neutrophil_count_unit=req.body.absolute_neutrophil_count_unit,
     result.immature_to_mature_neutrophil_ratios=req.body.immature_to_mature_neutrophil_ratios,
     result.thrombocytopenia_unit=req.body.thrombocytopenia_unit,
     result.thrombocytopenia=req.body.thrombocytopenia,
     result.urine_rest_for_pus_cells=req.body.urine_rest_for_pus_cells,
     result.urine_culture_test=req.body.urine_culture_test,
     result.blood_culture_report=req.body.blood_culture_report,
     result.gram_positive_bacteria=req.body.gram_positive_bacteria,
     result.gram_positive_bacteria_if_other=req.body.gram_positive_bacteria_if_other,
     result.gram_negative_bacteria=req.body.gram_negative_bacteria,
     result.gram_negative_bacteria_if_other=req.body.gram_negative_bacteria_if_other,
     result.fungi=req.body.fungi,
     result.other_organism=req.body.other_organism,
     result.antibiotic_status_resisitant=req.body.antibiotic_status_resisitant,
     result.antibiotic_status_intermediate=req.body.antibiotic_status_intermediate,
     result.antibiotic_status_value=req.body.antibiotic_status_value,
     result.sodium=req.body.sodium,
     result.potassium=req.body.potassium,
     result.chlorine=req.body.chlorine,
     result.calcium= req.body.calcium,
     result.phosphate= req.body.phosphate,
     result.magnesium=req.body.magnesium,
     result.urea=req.body.urea,
     result.creatinine=req.body.creatinine,
     result.lactate_levels=req.body.lactate_levels,
     result.bilirubin_levels=req.body.bilirubin_levels,
     result.cord_ph=req.body.cord_ph,
     result.arrhythmia=req.body.arrhythmia,
     result.csf_culture=req.body.csf_culture,
     result.csf_culture_tsb_value=req.body.csf_culture_tsb_value,
     result.tab_name=req.body.tab_name
     return result
}

}